FROM apache/spark:3.5.9

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip python3-psycopg2 python3-numpy \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/project
